{% set name = "arcplot" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arcplot-{{ version }}.tar.gz
  sha256: 0a85ac7336f8c42f1dfd57b7e0d64b63149f819866456661c0e3408905ca3001

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - poetry-core
    - pip
  run:
    - python >=3.10.0
    - contourpy 1.2.0
    - cycler 0.12.1
    - fonttools 4.48.1
    - kiwisolver 1.4.5
    - matplotlib-base 3.8.2
    - numpy 1.26.4
    - packaging 23.2
    - pillow 10.2.0
    - pyparsing 3.1.1
    - python-dateutil 2.8.2
    - six 1.16.0
    - pandas 2.2.1

test:
  imports:
    - arcplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/szkics/arcplot
  summary: arcplot is a library based on matplotlib for seamless creation of custom arc diagrams.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Matt-BF
